void mainmenu();
int strcount();
void sd();
void sh();
void searchadd(char ch[]);
void clearsearch();
void deletedirectory();
void createdirectory();
void response();
void delay(unsigned int);
void loading();
void dirappend();
void linedelete();
